package graphql.java.generator.argument.reflection;

import graphql.java.generator.argument.strategies.ArgumentDescriptionStrategy;

public class ArgumentDescription_ReflectionAutogen implements ArgumentDescriptionStrategy {
    
    @Override
    public String getArgumentDescription(Object object) {
        if (object instanceof Class<?>) {
            return getArgumentDescription((Class<?>) object);
        }
        return null;
    }
    
    protected String getArgumentDescription(Class<?> clazz) {
        return "Autogenerated from class [" + clazz.getCanonicalName() + "]";
    }
}
