package graphql.java.generator.argument.reflection;

import java.lang.reflect.Type;

import graphql.java.generator.argument.strategies.ArgumentDescriptionStrategy;

public class ArgumentDescription_ReflectionAutogen implements ArgumentDescriptionStrategy {
    
    @Override
    public String getArgumentDescription(Object object) {
        if (object instanceof Class<?>) {
            return getArgumentDescription((Class<?>) object);
        }
        else if (object instanceof Type) {
            return getArgumentDescription((Type) object);
        }
        return null;
    }
    
    protected String getArgumentDescription(Type type) {
        return "Autogenerated from type [" + type.toString() + "]";
    }
    
    protected String getArgumentDescription(Class<?> clazz) {
        return "Autogenerated from class [" + clazz.getCanonicalName() + "]";
    }
}
